# .bash_aliases

alias ls="eza -a --icons --group-directories-first --color=always"
alias ll="eza -la --icons --group-directories-first --color=always"
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -vI"
alias cat="bat"
alias cal="cal --sunday"
alias za="zathura --fork"
alias v="nvim"
alias sv="sudo nvim"
alias lf="lfcd"
alias nb="newsboat"
alias :q="exit"
alias g="googler -l en"
